import type { Meta, StoryObj } from '@storybook/react';
import { CostOverviewCard } from './CostOverviewCard';
declare const meta: Meta<typeof CostOverviewCard>;
export default meta;
type Story = StoryObj<typeof CostOverviewCard>;
export declare const Default: Story;
export declare const Loading: Story;
export declare const Skeleton: Story;
export declare const ErrorState: Story;
export declare const Empty: Story;
export declare const HighContrast: Story;
